### PR TITLE
Add support for custom container constant name

### LINKED ISSUE #21: Container constant to be configurable
In my current application, there is an ActiveRecord model named `Container`. This is unfortunately in conflict with dry-rails while booting and failed with `undefined method features for Container` since https://github.com/dry-rb/dry-rails/blob/23709e3a7cd08433480e85ab68189818d2af2af1/lib/dry/rails/railtie.rb#L73 loads model class.

## Examples

```ruby
Dry::Rails.container do
  config.container_constant = 'MyContainer'
end
```

### PR DESCRIPTION
**Pull request by diegotoral**
Closes #21

### CODE REVIEW

**Comment by solnic** [comment]
@diegotoral thanks for working on this one. Could you add a simple spec covering this functionality? Copying whatever we have for auto_inject_constant should do the trick.

**Comment by diegotoral** [comment]
@solnic I'm sorry! I totally forgot to mention the problems I've found while trying to test this feature. I can push the specs but what happens is that after changing the constant name to something else other specs start to fail as the code in dummy app still reference the old name.

I am not sure how to overcome this situation. :thinking:

**Comment by solnic** [comment]
@diegotoral no worries, please check `spec/integration/dry/rails/container_spec.rb` - doing something similar should work

**Comment by diegotoral** [comment]
@solnic that's exactly what I did (I hope :joy:) I pushed the spec so you can see the error.

**Comment by solnic** [comment]
@diegotoral damn :/ OK I'll take a look

**Comment by solnic** [comment]
@diegotoral OK this is too hard. Not worth the effort, at least not at the moment. Please just revert spec change and I'll merge this in.

**Comment by diegotoral** [comment]
Commit removed! :smile:

**Review by solnic — APPROVED** [review]

**Pull request merged**
